Fantasy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from menu.views import LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("menu.urls", namespace="menu")),
                  path("accounts/logout", LogoutView.as_view(), name="logouted"),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menu/urls.py
from django.urls import path

from menu.views import (
    index,
    RecipeListView,
    RecipeDetailView,
    GameListView,
    UserAccountCreateView,
    GameDetailView,
    UserAccountListView,
    UserAccountDetailView,
    RecipeCreateView,
    UserAccountFormView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "recipe/",
        RecipeListView.as_view(),
        name="recipe-list",
    ),
    path(
        "recipe/<int:pk>/",
        RecipeDetailView.as_view(),
        name="recipe-detail"
    ),
    path(
        "recipe/create/",
        RecipeCreateView.as_view(),
        name="recipe-create"
    ),
    path(
        "game/",
        GameListView.as_view(),
        name="game-list"
    ),
    path(
        "game/<int:pk>/",
        GameDetailView.as_view(),
        name="game-detail"
    ),
    path(
        "user/",
        UserAccountListView.as_view(),
        name="useraccount-list"
    ),
    path(
        "user/<int:pk>/",
        UserAccountDetailView.as_view(),
        name="useraccount-detail"
    ),
    path(
        "user/create/",
        UserAccountCreateView.as_view(),
        name="useraccount-create"),
    path(
        "user/<int:pk>/edit/",
        UserAccountFormView.as_view(),
        name="useraccount-edit"
    )
]

app_name = "menu"

templates/includes/footer_background.html
{% load static %}

<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class=" row">
      <div class="text-center">
        <div>
          <h6 class="text-gradient text-primary font-weight-bolder">Fantasy Gourmets</h6>
        </div>
      </div>
      <div class="">
        <div class="text-center">
          <p class="my-4 text-sm">
            &copy; <a href="https://github.com/KittNeKit" target="_blank">KittNeKit</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
{% load static %}
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
        class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
            href="/" rel="tooltip"
            title="Designed and Coded by Creative Tim" data-placement="bottom">
            Fantasy Gourmets
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a href="{% url 'menu:recipe-list' %}"
                    type="button" class="btn btn-outline-dark mb-0">Recipe</a>
              </li>

              <li class="nav-item dropdown dropdown-hover mx-2">
                <a href="{% url 'menu:game-list' %}"
                    type="button" class="btn btn-outline-dark mb-0">Games</a>
              </li>

              <li class="nav-item dropdown dropdown-hover mx-2">
                <a href="{% url 'menu:useraccount-list' %}"
                    type="button" class="btn btn-outline-dark mb-0">Users</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item ms-lg-auto">
                  <a href="{% url 'logouted' %}" target="_blank"
                  class="btn btn-lg bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">
                    <i class="fa fa-sign-out me-1"></i>Logout</a>
              </li>
              {% else %}
              <li class="nav-item ms-lg-auto">
                  <a href="{% url 'login' %}" target="_blank"
                  class="btn btn-lg bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">
                    <i class="fa fa-sign-in me-1"></i>Login</a>
              </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="row text-center py-2">
  <div class="col-4 mx-auto">
    <ul class="pagination pagination-primary m-4">
      {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">
              <i class="fa fa-angle-double-left" aria-hidden="true"></i>
            </a>
        </li>
      {% endif %}
      <li class="page-item">
        <span class="page-link">{{ page_obj.number }}/{{ paginator.num_pages }} </span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">
            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
           </a>
        </li>
    {% endif %}
    </ul>
  </div>
</div>

{% endif %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>

templates/includes/search_form.html
{% load crispy_forms_filters %}

 <form action="" method="get" class="form-inline">
     {{ search_form|crispy }}
       <div class="row text-center py-3 mt-3">
          <div class="col-4 mx-auto">
        </div>
      </div>
   </form>