Fantasy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from menu.views import LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("menu.urls", namespace="menu")),
                  path("accounts/logout", LogoutView.as_view(), name="logouted"),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menu/urls.py
from django.urls import path

from menu.views import (
    index,
    RecipeListView,
    RecipeDetailView,
    GameListView,
    UserAccountCreateView,
    GameDetailView,
    UserAccountListView,
    UserAccountDetailView,
    RecipeCreateView,
    UserAccountFormView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "recipe/",
        RecipeListView.as_view(),
        name="recipe-list",
    ),
    path(
        "recipe/<int:pk>/",
        RecipeDetailView.as_view(),
        name="recipe-detail"
    ),
    path(
        "recipe/create/",
        RecipeCreateView.as_view(),
        name="recipe-create"
    ),
    path(
        "game/",
        GameListView.as_view(),
        name="game-list"
    ),
    path(
        "game/<int:pk>/",
        GameDetailView.as_view(),
        name="game-detail"
    ),
    path(
        "user/",
        UserAccountListView.as_view(),
        name="useraccount-list"
    ),
    path(
        "user/<int:pk>/",
        UserAccountDetailView.as_view(),
        name="useraccount-detail"
    ),
    path(
        "user/create/",
        UserAccountCreateView.as_view(),
        name="useraccount-create"),
    path(
        "user/<int:pk>/edit/",
        UserAccountFormView.as_view(),
        name="useraccount-edit"
    )
]

app_name = "menu"

menu/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class TypeUser(models.Model):
    type = models.CharField(max_length=255)

    def __str__(self):
        return self.type


class UserAccount(AbstractUser):
    type_user = models.ForeignKey(
        TypeUser,
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("menu:useraccount-detail", kwargs={"pk": self.pk})


class Game(models.Model):
    name = models.CharField(max_length=255)
    about = models.TextField()

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.pk

    def get_absolute_url(self):
        return reverse("menu:game-detail", kwargs={"pk": self.pk})


class TypeOfDish(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    name = models.CharField(max_length=255)
    game_id = models.ForeignKey(Game, on_delete=models.CASCADE)
    ingredients = models.TextField()
    cooking_step = models.TextField()
    time_to_cook = models.IntegerField()
    type_of_dish = models.ForeignKey(TypeOfDish, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("menu:recipe-detail", kwargs={"pk": self.pk})

menu/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from menu.models import UserAccount, Recipe


class UserAccountCreationForm(UserCreationForm):
    class Meta:
        model = UserAccount
        fields = UserCreationForm.Meta.fields + ("type_user", "email")


class UserAccountEditForm(forms.ModelForm):
    class Meta:
        model = UserAccount
        fields = ("first_name",
                  "last_name",
                  "email",
                  "type_user",)


class UserAccountUsernameSearchForm(forms.Form):
    username = forms.CharField(max_length=255,
                               required=False,
                               label="",
                               widget=forms.TextInput(
                                   attrs={
                                       "placeholder": "Search by username.."
                                   })
                               )


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = "__all__"


class RecipeNameSearchForm(forms.Form):
    name = forms.CharField(max_length=255,
                           required=False,
                           label="",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Search by name.."
                               })
                           )


class GameNameSearchForm(forms.Form):
    name = forms.CharField(max_length=255,
                           required=False,
                           label="",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Search by name.."
                               })
                           )

menu/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from menu.forms import (
    UserAccountCreationForm,
    RecipeForm,
    UserAccountEditForm,
    UserAccountUsernameSearchForm,
    GameNameSearchForm,
    RecipeNameSearchForm
)
from menu.models import (
    Game,
    TypeOfDish,
    Recipe,
    UserAccount
)


def index(request):
    num_game = Game.objects.count()
    num_type_of_dish = TypeOfDish.objects.count()
    num_recipe = Recipe.objects.count()

    context = {
        "num_game": num_game,
        "num_type_of_dish": num_type_of_dish,
        "num_recipe": num_recipe
    }
    return render(request, "menu/index.html", context=context)


class RecipeListView(LoginRequiredMixin, generic.ListView):
    model = Recipe
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RecipeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = RecipeNameSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self):
        queryset = Recipe.objects.all()
        form = RecipeNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class RecipeDetailView(LoginRequiredMixin, generic.DetailView):
    model = Recipe


class RecipeCreateView(LoginRequiredMixin, generic.CreateView):
    model = Recipe
    form_class = RecipeForm
    success_url = reverse_lazy("menu:recipe-list")


class GameListView(LoginRequiredMixin, generic.ListView):
    model = Game

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = GameNameSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self):
        queryset = Game.objects.all()
        form = GameNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class GameDetailView(LoginRequiredMixin, generic.DetailView):
    model = Game

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameDetailView, self).get_context_data(**kwargs)
        recipe = Recipe.objects.filter(game_id=kwargs["object"].pk)
        context["recipe_list"] = recipe
        return context


class UserAccountCreateView(generic.CreateView):
    model = UserAccount
    form_class = UserAccountCreationForm
    template_name = "registration/sign-up.html"
    success_url = reverse_lazy("menu:index")


class UserAccountListView(LoginRequiredMixin, generic.ListView):
    model = UserAccount
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserAccountListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = UserAccountUsernameSearchForm(
            initial={
                "username": username
            }
        )
        return context

    def get_queryset(self):
        queryset = UserAccount.objects.all()
        form = UserAccountUsernameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )


class UserAccountDetailView(LoginRequiredMixin, generic.DetailView):
    model = UserAccount


class UserAccountFormView(LoginRequiredMixin, generic.UpdateView):
    model = UserAccount
    form_class = UserAccountEditForm
    success_url = reverse_lazy("menu:useraccount-list")


class LogoutView(generic.View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, "menu/index.html")

templates/menu/game_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>
    {{ game.name }}
  </title>
{% endblock %}

{% block content %}
  <header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/417947.jpg' %}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">{{ game.name }}</h1>
        </div>
      </div>
    </div>
  </div>
</header>
    <div class="container mt-sm-5 mt-3">
      <div class="row">
        <div class="col-lg-3">
          <div class="position-sticky pb-lg-5 pb-3 mt-lg-0 mt-5 ps-2" style="top: 100px">
            <h3>About game</h3>
          </div>
        </div>

      <div class="col-lg-9">
        <p class="lead text-dark mt-3">{{ game.about|linebreaks }}</p>
        </div>
      </div>
    </div>
      <div class="container mt-sm-5 mt-3">
    <div class="row">
      <div class="col-lg-3">
        <div class="position-sticky pb-lg-5 pb-3 mt-lg-0 mt-5 ps-2" style="top: 100px">
          <h3>Recipes</h3>
        </div>
      </div>

      <div class="col-lg-9">
        {% for recipe in recipe_list %}
          <a href={% url 'menu:recipe-detail' pk=recipe.pk %}>
            <p class="lead text-bg-primary mt-3">{{ recipe.name|linebreaks }}</p>
          </a>
        {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}

templates/menu/game_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>
  Games
  </title>
{% endblock %}

{% block content %}
  <header class="header-2">
  <div class="page-header mt-7 relative">
    <div class="container">
      <h1>
        Games
        {% include "includes/search_form.html" %}
      </h1>
      {% if game_list %}
        <table class="table">
          <tr>
            <th>ID</th>
            <th>Name</th>
          </tr>
        {% for game in game_list %}
          <tr>
            <td>{{ game.id }}</td>
            <td><a href="{{ game.get_absolute_url }}">{{ game.name }}</a></td>
          </tr>
        {% endfor %}

        </table>
    {% else %}
      <p>There are no games.</p>
    {% endif %}
    </div>
  </div>
  </header>

{% endblock %}

templates/menu/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>
  Home page
  </title>
{% endblock %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/417947.jpg' %}');">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">Fantasy gourmets</h1>
          <p class="lead text-white mt-3">a site that offers a rich collection of recipes for dishes from fantasy worlds.<br/> A huge fabulous cookbook that fits in your pocket. </p>
        </div>
      </div>
    </div>

    <div class="position-absolute w-100 z-index-1 bottom-0">
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="moving-waves">
          <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
          <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
          <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
          <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
        </g>
      </svg>
    </div>
  </div>
</header>


<section class="pt-3 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-dark text-primary"><span id="state1" countTo={{ num_recipe }}>0</span>+</h1>
              <h5 class="mt-3">Recipe</h5>
              <p class="text-sm">From games, that you can cook</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-dark text-primary"> <span id="state2" countTo={{ num_type_of_dish }}>0</span>+</h1>
              <h5 class="mt-3">Dishes</h5>
              <p class="text-sm">type, you can cook</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-dark text-primary" id="state3" countTo={{ num_game }}>0</h1>
              <h5 class="mt-3">Games</h5>
              <p class="text-sm">From which you can cook dishes</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- -------   START PRE-FOOTER 2 - simple social line w/ title & 3 buttons    -------- -->
<div class="pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 ms-auto">
        <h4 class="mb-1">If you wanna cook, or you wanna create a recipe,</h4>
        <h4 class="mb-1">You can register now!</h4>
      </div>
      <div class="col-lg-5 me-lg-auto my-lg-auto text-lg-end mt-5">
        <a href="{% url 'menu:useraccount-create' %}">
          <button type="button" class="btn bg-gradient-primary btn-lg">Register now!</button>
          </a>
      </div>
    </div>
  </div>
</div>




{% endblock content %}

{% block javascripts %}

<script type="text/javascript">

  if (document.getElementById('state1')) {
    const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
    if (!countUp.error) {
      countUp.start();
    } else {
      console.error(countUp.error);
    }
  }
  if (document.getElementById('state2')) {
    const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
    if (!countUp1.error) {
      countUp1.start();
    } else {
      console.error(countUp1.error);
    }
  }
  if (document.getElementById('state3')) {
    const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
    if (!countUp2.error) {
      countUp2.start();
    } else {
      console.error(countUp2.error);
    };
  }
</script>

{% endblock javascripts %}

templates/menu/recipe_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>
    {{ recipe.name }}
  </title>
{% endblock %}
{% block content %}
  <header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/417947.jpg' %}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">{{ recipe.name }}</h1>
        </div>
      </div>
    </div>
  </div>
</header>
    <div class="container mt-sm-5 mt-3">
    <div class="row">
      <div class="col-lg-3">
        <div class="position-sticky pb-lg-5 pb-3 mt-lg-0 mt-5 ps-2" style="top: 100px">
          <h3>Ingredients:</h3>
        </div>
      </div>

      <div class="col-lg-9">
        <p class="lead text-dark mt-3">{{ recipe.ingredients|linebreaks }}</p>
        </div>
      </div>
    </div>
      <div class="container mt-sm-5 mt-3">
    <div class="row">
      <div class="col-lg-3">
        <div class="position-sticky pb-lg-5 pb-3 mt-lg-0 mt-5 ps-2" style="top: 100px">
          <h3>Cooking step:</h3>
        </div>
      </div>

      <div class="col-lg-9">
        <p class="lead text-dark mt-3">{{ recipe.cooking_step|linebreaks }}</p>
        </div>
      </div>
    </div>

{% endblock %}

templates/menu/recipe_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
  <title>
  Create recipe
  </title>
{% endblock %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-10 relative">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-center">
              <h4 class="font-weight-bolder mt-7">Create Recipe</h4>
              <p class="mb-0">Field form to create your own recipe from game!</p>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form">
                {% csrf_token %}
               {{ form|crispy }}


                <div class="text-center">
                  <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Create!</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/menu/recipe_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>
  Recipe
</title>
{% endblock %}
{% block content %}
  <header class="header-2">
  <div class="page-header mt-7 relative">
    <div class="container">
      <h1>
        Recipes
        {% if user.type_user_id == 1 %}
        <a href="{% url 'menu:recipe-create' %}">
          <button type="submit" class="btn btn-lg bg-gradient-primary">add recipe!</button>
        </a>
        {% endif %}
      {% include "includes/search_form.html" %}
      </h1>
      {% if recipe_list %}
        <table class="table">
          <tr>
            <th>ID</th>
            <th>Recipe name</th>
            <th>Game</th>
            <th>Dish type</th>
            <th>Time to cook</th>
          </tr>
        {% for recipe in recipe_list %}
          <tr>
            <td>{{ recipe.id }}</td>
            <td><a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a></td>
            <td>{{ recipe.game_id.name }}</td>
            <td>{{ recipe.type_of_dish.name }}</td>
            <td>{{ recipe.time_to_cook }}</td>
          </tr>
        {% endfor %}

        </table>
    {% else %}
      <p>There are no recipe.</p>
    {% endif %}
    </div>
  </div>
  </header>

{% endblock %}

templates/menu/useraccount_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>
    {{ useraccount.username }}
  </title>
{% endblock %}

{% block content %}
  <header class="header-2">
  <div class="page-header mt-10 relative">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-dark pt-3 mt-5">Username: {{ useraccount.username }}</h1>
        </div>
      </div>
    </div>
  </div>
</header>
    <div class="container mt-sm-5 mt-3">
    <div class="row">
      {% if useraccount.first_name %}
        <p><strong>First name:</strong> {{ useraccount.first_name }}</p>
      {% endif %}
      {% if useraccount.first_name %}
        <p><strong>Last name:</strong> {{ useraccount.last_name }}</p>
      {% endif %}
        <p><strong>Type user:</strong> {{ useraccount.type_user }}</p>
      {% if useraccount.email %}
        <p><strong>Email:</strong> {{ useraccount.email }}</p>
      {% endif %}

    <h1>
      {% if user.id == useraccount.pk %}
        <a href="{% url 'menu:useraccount-edit' pk=user.id%}">
          <button type="submit" class="btn btn-lg bg-gradient-primary">edit</button>
        </a>
      {% endif %}
    </h1>
      </div>
    </div>

{% endblock %}

templates/menu/useraccount_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
  <title>
  Edit
  </title>
{% endblock %}

{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header mt-5 relative">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-center">
              <h4 class="font-weight-bolder mt-7">Edit information</h4>
              <p class="mb-0">Field form to edit your information..</p>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form">
                {% csrf_token %}
               {{ form|crispy }}

                <div class="text-center">
                  <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Edit!</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/menu/useraccount_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>
  Users
  </title>
{% endblock %}
{% block content %}
  <header class="header-2">
  <div class="page-header mt-7 relative">
    <div class="container">
      <h1>
        Users
        {% include "includes/search_form.html" %}
      </h1>
      {% if useraccount_list %}
        <table class="table">
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Type user</th>
          </tr>
        {% for useraccount in useraccount_list %}
          {% if useraccount.type_user%}
          <tr>
            <td>{{ useraccount.id }}</td>
            <td><a href="{{ useraccount.get_absolute_url }}">{{ useraccount.username }}</a></td>
            <td>{{ useraccount.type_user }}</td>
          </tr>
          {% endif %}
        {% endfor %}

        </table>
    {% else %}
      <p>There are no users.</p>
    {% endif %}
    </div>
  </div>
  </header>

{% endblock %}